### ISSUE TITLE
globalDefaults.cfg : maintain in this repo, make sure it's uploaded

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/management#10]
From https://github.com/DIRACGrid/DIRAC/issues/4604#issuecomment-630274040

Add globalDefaults.cfg (http://diracproject.web.cern.ch/diracproject/configs/globalDefaults.cfg) to this repo, and deploy to its current (and future) location(s) with the usual dirac-distribution container (like in https://github.com/DIRACGrid/Pilot/blob/master/.github/workflows/nightly.yml).

**Comment by atsareg** [comment]
Added globalDefaults.cfg here after cleaning it up from an obsoleted stuff

**Comment by chaen** [comment]
LHCb is obsolete ? :-) https://github.com/DIRACGrid/management/blob/master/globalDefaults.cfg#L98

**Comment by fstagni** [comment]
Consider https://github.com/DIRACGrid/DIRAC/issues/4820

**Comment by fstagni** [comment]
Check if dirac-install should be updated for using a list of locations, including CVMFS. @atsareg

**Comment by fstagni** [comment]
Also do the same to dirac-install.py (once it's maintained here) ?
