### ISSUE TITLE
Install of DIRAC versions in CVMFS

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/management#12]
In https://indico.cern.ch/event/927464/ it was asked if it would be possible to simply do “source bashrc” for “installing/setting up” DIRAC on CVMFS.
For vanilla DIRAC it could be possible, but then you need to anyway supply a specific configuration for the VO

**Comment by atsareg** [comment]
May be I have misunderstood the question but right now you can do:

    source /cvmfs/dirac.egi.eu/dirac/bashrc

to get the DIRAC environment from CVMFS. Yes, it should be customized for a particular DIRAC installation. In CVMFS there is a bunch of specific scripts like, for example, the one for EGI (/cvmfs/dirac.egi.eu/dirac/bashrc_egi):

    # Define EGI specific environment
    export DIRACSYSCONFIG=/cvmfs/dirac.egi.eu/dirac/egi.cfg
    
    source /cvmfs/dirac.egi.eu/dirac/bashrc
    
    export X509_VOMS_DIR=/cvmfs/dirac.egi.eu/dirac/etc/grid-security/vomsdir
    export X509_CERT_DIR=/cvmfs/dirac.egi.eu/dirac/etc/grid-security/certificates

and /cvmfs/dirac.egi.eu/dirac/egi.cfg:

    DIRAC
    {
      Setup = EGI-Production
      Configuration
      {
        Servers = dips://dirac-config.egi.eu:9135/Configuration/Server
        Master = no
      }
    }

The specific scripts can be sourced from the local environment, not necessarily taken from CVMFS. This way one can customize the DIRAC client for any installation

**Comment by fstagni** [comment]
This was mostly a question from @IgorPelevanyuk. 
@IgorPelevanyuk Is that what you were expecting?

**Comment by fstagni** [comment]
There were no reply to this ticket, and seems to me already "solved". So, I close, please comment further if you think it should be re-opened.
