### ISSUE TITLE
Move images to GitHub container registry

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/management#21]
Since there is now a [rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) on dockerhub , we should adopt [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) and it's better then the GitHub Package Registry which does not allow anonymous pulls.

**Comment by fstagni** [comment]
Do we pull often from docker hub? I think our main user of the uploaded containers is GitHub Actions. 

Anyway: of course fine, we can adopt the new GitHub Container Registry.

**Comment by petricm** [comment]
I don't know how many pulls there are generated by one CI pass through. Of course we should still publish to dockerhub but for the CI we should use GitHub.

The problem is not how much we pull, but since we pull anonymous "Unauthenticated (anonymous) users will have the limits enforced via IP." and "unauthenticated users: 100 pulls per 6 hours". So depending on the CI node you land on you actually don't know how close or far you are from the limit.

**Comment by petricm** [comment]
So this is two fold:
- [x] Publish to GitHub registry (done in #22)
- [x] Fix the CI yml to use this image (open PR DIRACGrid/DIRAC#4803 and DIRACGrid/DIRAC#4804)

**Comment by fstagni** [comment]
I think this can be closed.
