### ISSUE TITLE
Pilot/dirac-install.py for X509_VOMS*

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/management#52]
Seeing #50 and #51, I am wondering if it is better apply the same to Pilot/dirac-install.py, or if there is a reason to keep `X509_VOMS_DIR="/etc/grid-security/vomsdir"` and `X509_VOMSES="/etc/vomses"`?

This may not be relevant if pilot does not contact VOMS (proxies to be provided rather than to be created on WN), but better be consistent with management/dirac-install.py...?

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/Pilot/pull/145
