### ISSUE TITLE
dirac-install.py fails with python3.12 due to removed module imp

### ISSUE THREAD

**Issue by davehadley** [DIRACGrid/management#59]
Running `dirac-install` with python 3.12 raises the error:

```
ModuleNotFoundError: No module named 'imp'
```

The problem is caused by [the usage of the `imp` module that was removed in python 3.12](https://github.com/DIRACGrid/management/blob/a1b39b27dbef311aea8c6647392a5746db150668/dirac-install.py#L140).

The [python 3.11 documentation for the imp module](https://docs.python.org/3.11/library/imp.html) says that users should migrate to the [importlib module](https://docs.python.org/3/library/importlib.html).

**Comment by fstagni** [comment]
I am not sure how you reached this (this is most probably our fault not properly documenting/advertising) but `dirac-install` is only a py2 tool. It's in some of the containers here but unmaintained. 

The way you install a py3 DIRAC client is in https://dirac.readthedocs.io/en/latest/UserGuide/GettingStarted/InstallingClient/index.html

We have not yet tested for python 3.12 though. Our conda-based installer uses 3.11 (https://github.com/DIRACGrid/DIRACOS2/blob/acec2baa3a35aa2dc164408c1658bd4205250ef6/construct.yaml#L36) and DIRAC is only 3.9, 3.10, 3.11: https://pypi.org/project/DIRAC/

If this issues is just for asking to port to 3.12 too, we'll do at some point.

**Comment by davehadley** [comment]
OK thanks for the info. I guess I was following out of date instructions that have not been updated for the new installation method.
