### ISSUE TITLE
dirac-distribution: use diraccfg

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/management#6]
Instead of adding dirac-install in
https://github.com/DIRACGrid/management/blob/master/dirac-distribution/Dockerfile#L45

and using it in https://github.com/DIRACGrid/management/blob/master/dirac-distribution/dirac-distribution.py#L19

use `diraccfg`. Later the same dirac-install.py (in DIRAC) can be simplified.

**Comment by petricm** [comment]
I looked into this, but `dirac-distribution` relies on some additional functionality that is in in `ReleaseConfig` and not currently part of `diraccfg`. So now there are two options:
 - port the rest from `ReleaseConfig` to `diraccfg`
 - Re-implement on several places in `dirac-distribution` the logic from `ReleaseConfig`

I don't know how "clean" you want to keep `diraccfg`?

**Comment by fstagni** [comment]
In the OP (wrote 10 months ago) I thought about "simplifying" dirac-install. Now we are thinking about removing it completely. 
Probably it does not make much sense to invest time in this task...

Thank you for looking into it. I think there are more pressing tasks, and I close this one.
