### ISSUE TITLE
dirac-distribution doesn't build WebApp when module name doesn't contain 'Web'

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/management#9]
dirac-distribution switches the WebApp build behavior by the module name:
`        if 'Web' in modName:    # we have to compile WebApp and also its extension.`

If this behavior can be controlled by other flag (e.g. script option), we can choose whether WebApp binaries are contained, independently from the module name.

What do you think?

**Comment by fstagni** [comment]
Yes, it is certainly possible, and it would be the way to go. Would you give it a try, with your case in mind?

**Comment by fstagni** [comment]
@hmiyake did you sort out this issue?

**Comment by hmiyake** [comment]
Unfortunately I myself couldn't find time for the issue. Since now we are building our WebApp extension with current implementation (by some tricks), this modification won't be expected in short time scale. Let me close the ticket for now.
